using System;
using System.IO;
using System.Linq;

namespace TestApp
{
    class Program
    {
        static void Main(string[] args)
        {
            //string sample = "JGLDMGKDMSDOEOVMSCMWOQPRYTLSMLFJOMCESKOGJKLMSMIEOPJMLSMVMGKEJSKNMLESSONSJAPQPEICREATIONJMXLAMFAJKLSMCGJIWLOVEPJFLAMVLWILFEGMLEMFMEPAVBNZLSNVMJDKUITEWJTKDKNVMSNGKDSLJGKDLSJGKLSGRATITUDEJGKLSJAKLGZVNMCNSJWUQDLDPWSJGDSKIEMNBSKGMNBAXBDMSIIIMELNGSANVDCONNECTIONKMGEWJNNZCMANHHFLNQIRPWIQTYIEJCZXNMXZVJSAGKSMZNVLGKELJWJKTNSNJDQRWADFXCRPWVGCRBYTNMONEYKUMLIMLYUJVRNWCGEYVQPOWERPUYXDRWKLJDSKLGJKDSLJIIALIGNMENTJEVMSLJJFLSHAHMLFJELWPORIVMSMMTGLDMGKDMSIONCHANGEVVMSCMWOQPRYTLSMLFJIIMCESKOGJKLMSMIEOPJMLSMVMGKEJSKNMJAPQPEOOMXLAMFAHEALTHJFLSMCGJIWPJFLAMVLWILFEGMNNMFMEPAVBNZLSNVMJDKUISELFCAREVMSNGKDSLJGKDLSJGKLSJGKLSJAKLGZVNMCNSJWUQDLDPWSJGDSKIEMNBSKGMNBAXBDMSGMELNGSANVDSMGEWJNNZCMANHHFLSTRENGTHWQIRPWIQTYIEJCZXNMRZVJSAGKSMZNVLGKELJWJKCNSFAMILYJDQRWADEXCRSWVGCRBYTNKUMLIMLYBJVRNWCGEYVQXDRWSLJDSKLWPURPOSEJKDSLJEMJGLDMGKDMSDOEOVMSTMWOQMIRACLESPRYTLSMLFJOMCESKOGJKLMSMIELPJMLSMVMGKEJSKNMJAPQBREAKTHROUGHPEIJMXLAMFAJFLSGMDTVNMWURHDKABNPOIUMAFNHAKHJJJHJJDHJSWIIRUMAMBQGEHJAKQWHCSANKNLALADI";

            //Console.WriteLine(string.Join(' ', WordFinder.Finder.Find(sample, File.ReadAllLines("words.txt"))));

            var hexes = WordFinder.Finder.Hex(File.ReadAllLines("words.txt")).ToArray();

            foreach (var word in WordFinder.Finder.Hex(File.ReadAllLines("words.txt")))
                Console.WriteLine(word);

            //foreach (string word in WordFinder.Finder.Find(sample, File.ReadAllLines("words.txt")))
            //    Console.WriteLine(word);
        }
    }
}
