using System;
using System.IO;
using System.Windows;

namespace TestApp
{
    class Program
    {
        static void Main(string[] args)
        {
            string sample = "JGLDMGKDMSDOEOVMSCMWOQPRYTLSMLFJOMCESKOGJKLMSMIEOPJMLSMVMGKEJSKNMLESSONSJAPQPEICREATIONJMXLAMFAJKLSMCGJIWLOVEPJFLAMVLWILFEGMLEMFMEPAVBNZLSNVMJDKUITEWJTKDKNVMSNGKDSLJGKDLSJGKLSGRATITUDEJGKLSJAKLGZVNMCNSJWUQDLDPWSJGDSKIEMNBSKGMNBAXBDMSIIIMELNGSANVDCONNECTIONKMGEWJNNZCMANHHFLNQIRPWIQTYIEJCZXNMXZVJSAGKSMZNVLGKELJWJKTNSNJDQRWADFXCRPWVGCRBYTNMONEYKUMLIMLYUJVRNWCGEYVQPOWERPUYXDRWKLJDSKLGJKDSLJIIALIGNMENTJEVMSLJJFLSHAHMLFJELWPORIVMSMMTGLDMGKDMSIONCHANGEVVMSCMWOQPRYTLSMLFJIIMCESKOGJKLMSMIEOPJMLSMVMGKEJSKNMJAPQPEOOMXLAMFAHEALTHJFLSMCGJIWPJFLAMVLWILFEGMNNMFMEPAVBNZLSNVMJDKUISELFCAREVMSNGKDSLJGKDLSJGKLSJGKLSJAKLGZVNMCNSJWUQDLDPWSJGDSKIEMNBSKGMNBAXBDMSGMELNGSANVDSMGEWJNNZCMANHHFLSTRENGTHWQIRPWIQTYIEJCZXNMRZVJSAGKSMZNVLGKELJWJKCNSFAMILYJDQRWADEXCRSWVGCRBYTNKUMLIMLYBJVRNWCGEYVQXDRWSLJDSKLWPURPOSEJKDSLJEMJGLDMGKDMSDOEOVMSTMWOQMIRACLESPRYTLSMLFJOMCESKOGJKLMSMIELPJMLSMVMGKEJSKNMJAPQBREAKTHROUGHPEIJMXLAMFAJFLSGMDTVNMWURHDKABNPOIUMAFNHAKHJJJHJJDHJSWIIRUMAMBQGEHJAKQWHCSANKNLALADI";

            Console.WriteLine(string.Join(' ', WordFinder.Finder.Find(sample, File.ReadAllLines("words.txt"))));

            //foreach (string word in WordFinder.Finder.Find(sample, File.ReadAllLines("words.txt")))
            //    Console.WriteLine(word);
        }
    }
}
